---
title: "Statistical Linear Models Project 2"
subtitle: "Math 158, Linear Models, Spring 2018"
author: "Moira Dillon & Mike Adams"
date: "Due: Monday, February 12, 2018"
output:
   pdf_document:
       latex_engine: xelatex
---


\section*{Introduction}

# Briefly refresh the reader’s mind as to the variables of interest

We are analyzing The Lahman Baseball Database, available on R. This database includes pitching, hitting, and fielding stats for Major League Baseball from 1871 through 2016. We will be analyzing players salaries, awards, statistics for batting & fielding during regular and post season, along with their birth date, height, weight, playing hand, and birth country.

In order to analyze independent observational units, we will just be considering the last year of data for each player in the data set. Because each player shows up in the data set multiple times (multiple years playing professional baseball), the original data is not independent. However, by comparing variables using the last year of each player's career as the observational unit, the data is independent. 

Additionally, we have subsetted the data further because of some missing entries. Batting statistics are not complete until 1955 and salary records do not begin until 1985. Additionally, there are a handful of missing values for each other variable. 

using complete.cases() == filtered out all the NAs  -- down to 3557 rows

\section*{Introduction}

# The hypotheses that you’ll be addressing. It will probably be that the two variables are linearly related. (Positively? Negatively? Remember, R gives a two-sided p-value, but you can just as easily test that β1 > 0 or β1 < 0.)

We will use linear regression to determine if there is a linear relationship between salary and number of home runs (for the last year of each player's career). 

```{r, eval=TRUE}
# data set of just last year of every player 
filtered_lahman <- read.csv("Lahman_filtered.csv", header=TRUE)

filtered_lahman <- filtered_lahman[complete.cases(filtered_lahman), ]

ggplot(filtered_lahman, aes(filtered_lahman$G,filtered_lahman$HR)) + geom_point()
```

