---
title: "Statistical Linear Models Project 1"
subtitle: "Math 158, Linear Models, Spring 2018"
author: "Moira Dillon & Mike Adams"
date: "Due: Monday, February 5, 2018"
output: pdf_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("Lahman")
require(Lahman)
```

We will be analyzing The Lahman Baseball Database, available on R. This database includes pitching, hitting, and fielding stats for Major League Baseball from 1871 through 2016. This dataset is the largest available for baseball statistics. Specifically, this data set includes information on batting, pitching, fielding, all-star statistics, hall of fame, managers, teams, batting, pitching, and fielding in the post season, franchises, managers, salaries, awards, school history, in addition to a handful of other factors. 

Specifically, we will be analyzing players salaries, awards, statistics for batting & fielding during regular and post season, along with their birth date, height, weight, playing hand, and birth country.

While there are various analyses we will be able to conduct with this data, there are a few in particular we are looking forward to. We are interested in the relationship between playing statistics (batting & fielding) and recognition of success (awards & salaries), specifically how this may change over time. We are also interested in analyzing birth month & playing statistics, as Malcolm Gladwell suggests in \textit{Outliers} that players born earlier in the calender year tend to be more likely to reach the professional level.

Our Github repository for this project is available here: https://github.com/moiradillon2/SLM_MAMD/





